# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM oven/bun:alpine
WORKDIR /app

# Copy package files and install dependencies
COPY package.json bun.lock ./
RUN bun install

# Copy the rest of the application
COPY . .

# Build the project
RUN bun run build

# Expose a port if needed (optional)
# EXPOSE 3000

# Start the MCP server
CMD ["bun", "dist/index.js"]
